server:
  port: 8080
  servlet:
    contextPath: /
  
logging:
  level:
    root: INFO
    com.swayam.ocr.porua: DEBUG
    org.springframework.web: INFO

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  datasource:
    url: jdbc:postgresql://192.168.1.4:5432/tesseract-porua
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/sql/liquibase/master-change-log.xml

springdoc:
  swagger-ui.path: /swagger-ui.html
