CREATE MEMORY TABLE IF NOT EXISTS raw_image ( 
	id INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1) PRIMARY KEY, 
	name VARCHAR(200) UNIQUE NOT NULL,
	language VARCHAR(25) NOT NULL
);

CREATE MEMORY TABLE IF NOT EXISTS ocr_word ( 
	id INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1) PRIMARY KEY, 
	raw_ocr_word OTHER NOT NULL,
	corrected_text CLOB,
        raw_image_id INTEGER NOT NULL,
	FOREIGN KEY (raw_image_id) REFERENCES raw_image (id)
);
