CREATE MEMORY TABLE IF NOT EXISTS script ( id TINYINT GENERATED ALWAYS AS IDENTITY(START WITH 1) PRIMARY KEY, name VARCHAR(20)  NOT NULL );

CREATE MEMORY TABLE IF NOT EXISTS typeface ( 
	id INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1) PRIMARY KEY, 
	name VARCHAR(20) UNIQUE NOT NULL,
	description VARCHAR(100),   
	script_id TINYINT,
	FOREIGN KEY (script_id) REFERENCES script (id)
);

CREATE MEMORY TABLE IF NOT EXISTS glyph ( 
	id INTEGER GENERATED ALWAYS AS IDENTITY(START WITH 1) PRIMARY KEY, 
	binary_image OTHER NOT NULL,
	unicode VARCHAR(100) NOT NULL,
	description VARCHAR(100),   
	typeface_id INTEGER,
	FOREIGN KEY (typeface_id) REFERENCES typeface (id)
);
