version: '3'

services:
    aggregator_1:
        image: paawak/kafka-camel-aggregation-with-replay:latest
        ports:
          - "8080:8080"
        environment:
          - spring.profiles.active=default
          - processorId=camel_8080
        networks:
          - paawak-net                
            
    aggregator_2:
        image: paawak/kafka-camel-aggregation-with-replay:latest
        ports:
          - "8081:8080"
        environment:
          - spring.profiles.active=default
          - processorId=camel_8081
        networks:
          - paawak-net  
          
    simple_publisher:
        image: paawak/kafka-simple-publisher:latest
        ports:
          - "8090:8090"
        environment:
          - spring.profiles.active=default
        networks:
          - paawak-net                       

networks:
    paawak-net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24


